FROM python:3.13-slim AS  builder

RUN mkdir /app

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


COPY requirements.txt /app/

RUN pip install --upgrade pip && \
    pip install --prefix=/install -r requirements.txt



FROM python:3.13-slim AS producer

WORKDIR /app

COPY --from=builder /install /usr/local

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . .



EXPOSE 8000

CMD ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]