services:
  db:
   image: postgres:17
   environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
   ports:
      - "5432:5432"
   env_file:
    - .env

  
  redis:
    image: redis
    ports:
      - "6379:6379"
  
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      - redis

    env_file:
      - .env
