# Generated by Django 6.0.3 on 2026-03-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='location',
        ),
    ]
