# Generated by Django 6.0.3 on 2026-03-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='customer',
        ),
    ]
