# Generated by Django 6.0.3 on 2026-03-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_payment_delete_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='otp',
        ),
        migrations.AddField(
            model_name='booking',
            name='arrival_otp',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='completion_otp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('cash', 'Cash')], default='online'),
        ),
    ]
