# Generated by Django 6.0.3 on 2026-03-16 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_otp_booking_arrival_otp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorypay_order_id',
            new_name='razorpay_order_id',
        ),
    ]
